
# Week 9 – Chatbot Development

## Project Title
Education AI Chatbot using Python and Ollama

## Objective
- To develop an interactive AI chatbot.
- To use Ollama and a local language model.
- To test the chatbot using sample questions.
- To store questions and responses in CSV files.
- To evaluate the strengths and limitations of the chatbot.

In [10]:

import os
import csv
import pandas as pd
import ollama
from datetime import datetime

print("All libraries imported successfully!")

All libraries imported successfully!

In [11]:

# Find the project directory
current_dir = os.getcwd()

if os.path.basename(current_dir).lower() == "notebook":
    project_dir = os.path.dirname(current_dir)
else:
    project_dir = current_dir

dataset_dir = os.path.join(project_dir, "dataset")
os.makedirs(dataset_dir, exist_ok=True)

questions_file = os.path.join(dataset_dir, "sample_questions.csv")
history_file = os.path.join(dataset_dir, "chat_history.csv")
responses_file = os.path.join(dataset_dir, "responses.csv")

print("Project folder:", project_dir)
print("Dataset folder:", dataset_dir)

Project folder: c:\Users\Lenovo\Desktop\LLm tasks\Chatbot_development
Dataset folder: c:\Users\Lenovo\Desktop\LLm tasks\Chatbot_development\dataset

In [12]:

sample_questions = [
    "What is Python?",
    "What is Artificial Intelligence?",
    "What is Machine Learning?",
    "What is a Large Language Model?",
    "What is a database?",
    "What is DBMS?",
    "What is SQL?",
    "What is a primary key?",
    "What is a foreign key?",
    "What is normalization in DBMS?",
    "What is a Python variable?",
    "What is a Python function?",
    "What is a loop in Python?",
    "What is a list in Python?",
    "What is an algorithm?",
    "What is a data structure?",
    "What is cloud computing?",
    "What is cybersecurity?",
    "Explain the difference between AI and ML.",
    "Write a Python program to add two numbers."
]

questions_df = pd.DataFrame(sample_questions, columns=["question"])
questions_df.to_csv(questions_file, index=False)

print("Sample questions created successfully!")
print("Total questions:", len(questions_df))
display(questions_df)

Sample questions created successfully!
Total questions: 20

                                      question
0                              What is Python?
1             What is Artificial Intelligence?
2                    What is Machine Learning?
3              What is a Large Language Model?
4                          What is a database?
5                                What is DBMS?
6                                 What is SQL?
7                       What is a primary key?
8                       What is a foreign key?
9               What is normalization in DBMS?
10                  What is a Python variable?
11                  What is a Python function?
12                   What is a loop in Python?
13                   What is a list in Python?
14                       What is an algorithm?
15                   What is a data structure?
16                    What is cloud computing?
17                      What is cybersecurity?
18   Explain the difference between AI and ML.
19  Write a Python program to add two numbers.

In [13]:

MODEL = "llama3.2:1b"

test_question = "What is Python? Explain in simple English."

response = ollama.chat(
    model=MODEL,
    messages=[
        {
            "role": "system",
            "content": (
                "You are an education assistant. "
                "Answer in simple English with clear examples. "
                "If you are unsure, say so."
            )
        },
        {"role": "user", "content": test_question}
    ]
)

print("Question:", test_question)
print("Chatbot Response:", response["message"]["content"])

Question: What is Python? Explain in simple English.
Chatbot Response: Python is a computer programming language. It's like a recipe to write instructions for a computer to follow.

Imagine you want to make a sandwich. You need to follow some steps:

1. Take two slices of bread.
2. Put some meat on one slice.
3. Add some cheese on top.

You write down these steps in a list, and then you repeat them to make the sandwich.

Python is like that. It's a programming language that helps you write instructions (called "code") for computers to follow. You write the code, and then you tell the computer to do the things the code says.

Python is easy to learn and use, and it's used by many people to do all sorts of things, like:

* Making games
* Creating websites
* Analyzing data
* Learning about science and math

Some people like to use Python because it's fun and easy to play with, like building with blocks or playing with Legos. Others like to use it because it's powerful and can help them do really cool things!

In [14]:

import pandas as pd
import os

questions = [
    "What is Python?",
    "What is Artificial Intelligence?",
    "What is Machine Learning?",
    "What is a Large Language Model?",
    "What is a database?",
    "What is DBMS?",
    "What is SQL?",
    "What is a primary key?",
    "What is a foreign key?",
    "What is normalization in DBMS?",
    "What is a Python variable?",
    "What is a Python function?",
    "What is a loop in Python?",
    "What is a list in Python?",
    "What is an algorithm?",
    "What is a data structure?",
    "What is cloud computing?",
    "What is cybersecurity?",
    "Explain the difference between AI and ML.",
    "Write a Python program to add two numbers."
]

questions_df = pd.DataFrame(questions, columns=["question"])

print("Total questions:", len(questions_df))
display(questions_df)

Total questions: 20

                                      question
0                              What is Python?
1             What is Artificial Intelligence?
2                    What is Machine Learning?
3              What is a Large Language Model?
4                          What is a database?
5                                What is DBMS?
6                                 What is SQL?
7                       What is a primary key?
8                       What is a foreign key?
9               What is normalization in DBMS?
10                  What is a Python variable?
11                  What is a Python function?
12                   What is a loop in Python?
13                   What is a list in Python?
14                       What is an algorithm?
15                   What is a data structure?
16                    What is cloud computing?
17                      What is cybersecurity?
18   Explain the difference between AI and ML.
19  Write a Python program to add two numbers.

In [15]:

results = []

for question in questions_df["question"].dropna():
    try:
        response = ollama.chat(
            model=MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an education assistant. "
                        "Answer in simple English. "
                        "Give correct and relevant answers. "
                        "If you are unsure, say so."
                    )
                },
                {"role": "user", "content": question}
            ]
        )

        answer = response["message"]["content"]
        status = "Success"

    except Exception as error:
        answer = str(error)
        status = "Error"

    results.append({
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "question": question,
        "response": answer,
        "status": status
    })

    print("Question:", question)
    print("Response:", answer)
    print("-" * 50)

responses_df = pd.DataFrame(results)
responses_df.to_csv(responses_file, index=False)

print("Testing completed!")
print("Total tested:", len(responses_df))
print("Successful responses:", (responses_df["status"] == "Success").sum())
print("Saved to:", responses_file)

Question: What is Python?
Response: Python is a simple computer programming language. It's like a recipe for making things happen on a computer. It's easy to learn and use, so many people use it for all sorts of things.

Imagine you want to build a website or play a game. Python can help you do that. It's like a special set of instructions that the computer can understand. You can write the instructions in a language called "code," and the computer will follow them to make something happen.

Python is often used for things like:

* Building websites and web applications
* Creating games
* Analyzing data
* Helping scientists and researchers

It's a very popular language, and many people learn it because it's easy to use and has a lot of resources available.

Do you want to learn more about Python?
--------------------------------------------------

KeyboardInterrupt:

In [16]:

import pandas as pd
import os

if results:
    responses_df = pd.DataFrame(results)

    output_path = os.path.join(dataset_dir, "responses.csv")
    responses_df.to_csv(output_path, index=False)

    print("Results saved successfully!")
    print("Total records:", len(responses_df))
    print("Saved location:", output_path)

    display(responses_df.head())
else:
    print("No results found. Run the testing cell first.")

Results saved successfully!
Total records: 1
Saved location: c:\Users\Lenovo\Desktop\LLm tasks\Chatbot_development\dataset\responses.csv

,timestamp,question,response,status
0,2026-10-28T19:23:12,What is Python?,Python is a simple computer programming langua...,Success


## Strengths

1. The chatbot answers educational questions.
2. It uses a locally running AI model.
3. It supports continuous interaction.
4. It saves questions and responses in CSV files.

## Limitations

1. Some answers may be incorrect.
2. Response speed depends on the computer.
3. Ollama must be running to generate responses.
4. The chatbot requires further testing to improve accuracy.

## Conclusion

This project helped me understand how to develop and test an AI chatbot using Python and Ollama. The chatbot generates educational responses and stores the results for analysis.

In [17]:

from datetime import datetime

print("Datetime imported successfully!")

Datetime imported successfully!

In [18]:
from datetime import datetime

In [19]:

responses_df = pd.DataFrame(results)

print("Total questions tested:", len(responses_df))
print("\nTest Status:")
print(responses_df["status"].value_counts())

display(responses_df.head())

Total questions tested: 1

Test Status:
status
Success    1
Name: count, dtype: int64

,timestamp,question,response,status
0,2026-10-28T19:23:12,What is Python?,Python is a simple computer programming langua...,Success

In [20]:

print("Number of results:", len(results))
print("Results:", results[:2])

Number of results: 1
Results: [{'timestamp': '2026-10-28T19:23:12', 'question': 'What is Python?', 'response': 'Python is a simple computer programming language. It\'s like a recipe for making things happen on a computer. It\'s easy to learn and use, so many people use it for all sorts of things.\n\nImagine you want to build a website or play a game. Python can help you do that. It\'s like a special set of instructions that the computer can understand. You can write the instructions in a language called "code," and the computer will follow them to make something happen.\n\nPython is often used for things like:\n\n* Building websites and web applications\n* Creating games\n* Analyzing data\n* Helping scientists and researchers\n\nIt\'s a very popular language, and many people learn it because it\'s easy to use and has a lot of resources available.\n\nDo you want to learn more about Python?', 'status': 'Success'}]

In [21]:

if results:
    responses_df = pd.DataFrame(results)

    print("Total questions tested:", len(responses_df))
    print("Available columns:", list(responses_df.columns))

    if "status" in responses_df.columns:
        print("\nTest Status:")
        print(responses_df["status"].value_counts())
    else:
        print("\nStatus column is missing. Check the testing code.")

    display(responses_df.head())

else:
    print("No results available. Please run the 20-question testing cell first.")

Total questions tested: 1
Available columns: ['timestamp', 'question', 'response', 'status']

Test Status:
status
Success    1
Name: count, dtype: int64

,timestamp,question,response,status
0,2026-10-28T19:23:12,What is Python?,Python is a simple computer programming langua...,Success